import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    mapContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    map: {
        flex: 1,
    },
    menuButton: {
        position: "absolute",
        top: Platform.OS === 'ios' ? 50 : 30,
        left: 20,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        padding: 12,
        borderRadius: 50,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        zIndex: 6,
    },
    sidebar: {
        position: "absolute",
        top: 0,
        left: -300, // Hidden initially
        width: 280,
        height: "100%",
        backgroundColor: "#fff",
        paddingTop: Platform.OS === 'ios' ? 50 : 30,
        paddingBottom: 30,
        paddingHorizontal: 20,
        borderRightWidth: 0,
        shadowColor: "#000",
        shadowOffset: { width: 3, height: 0 },
        shadowOpacity: 0.27,
        shadowRadius: 4.65,
        elevation: 8,
        zIndex: 10,
    },
    closeButton: {
        position: "absolute",
        top: Platform.OS === 'ios' ? 50 : 30,
        right: 15,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        padding: 10,
        borderRadius: 50,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 4,
        zIndex: 11,
    },
    mapOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.15)',
        zIndex: 5,
    },
    profileContainer: {
        alignItems: "center",
        marginTop: 25,
        marginBottom: 30,
        paddingBottom: 25,
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    avatarContainer: {
        width: 90,
        height: 90,
        borderRadius: 45,
        overflow: "hidden",
        marginBottom: 15,
        borderWidth: 3,
        borderColor: "#8A2BE2",
        shadowColor: "#8A2BE2",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
    },
    // Improved avatar menu styling
    avatarMenuContainer: {
        position: "absolute",
        top: Platform.OS === "ios" ? 50 : 30,
        right: 20,
        zIndex: 10,
    },
    avatarSmall: {
        width: 50,
        height: 50,
        borderRadius: 30,
        borderWidth: 2,
        borderColor: "#FFE4F3",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 8,
    },
    avatarButtonContainer: {
        shadowColor: "#FFE4F3",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    menuOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 9,
    },
    avatar: {
        width: "100%",
        height: "100%",
    },
    username: {
        fontSize: 19,
        fontWeight: "700",
        color: "#333",
        marginBottom: 4,
    },
    userRole: {
        fontSize: 15,
        color: "#777",
        fontWeight: "500",
    },
    menuSection: {
        marginBottom: 20,
    },
    menuItem: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 16,
        paddingHorizontal: 10,
        borderRadius: 12,
        marginVertical: 5,
    },
    menuText: {
        fontSize: 16,
        marginLeft: 15,
        color: "#333",
        fontWeight: "500",
    },
    logoutButton: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 30,
        paddingVertical: 14,
        backgroundColor: "#fff",
        borderRadius: 12,
        paddingHorizontal: 20,
        justifyContent: "center",
        shadowColor: "#8A2BE2",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 6,
    },
    logoutText: {
        fontSize: 16,
        color: "#FF69B4",
        marginLeft: 10,
        fontWeight: "600",
    },
    
    footer: {
        position: "absolute",
        bottom: 0,
        width: "100%",
        backgroundColor: "#FFE4F3",
        padding: 20,
        paddingTop: 25,
        paddingBottom: Platform.OS === 'ios' ? 35 : 25,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 10,
        zIndex: 5,
    },
    input: {
        width: "100%",
        height: 50,
        backgroundColor: "#fff",
        borderRadius: 12,
        paddingHorizontal: 15,
        marginBottom: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 2,
        borderWidth: 1,
        borderColor: "#f0f0f0",
        fontSize: 15,
    },
    confirmButton: {
        backgroundColor: '#fff', // Fondo rosa claro
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
        marginTop: 16, // Espaciado superior
        alignSelf: 'center', // Centra el botón horizontalmente
        width: '90%', // Ancho del botón
    },
    confirmButtonText: {
        color: '#FF69B4', // Texto rosa oscuro
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    buttonText: {
        color: "#FF69B4",
        fontSize: 16,
        fontWeight: "700",
        letterSpacing: 0.5,
    },
});

export default styles;